# Generated by Django 4.2.6 on 2023-10-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='arquivo_pdf',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
